services:
  - type: web
    name: farm-animals-shop
    env: java
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/app.jar"
    rootDir: .
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: deploy