# 베이스 이미지로 OpenJDK 17 (Alpine 기반)을 사용
FROM openjdk:17-jdk-alpine

# JAR 파일을 컨테이너에 복사 (빌드 후 생성된 파일 이름에 맞춰 수정)
COPY build/libs/farm_animals_shop-0.0.1-SNAPSHOT.jar /app/app.jar

# 애플리케이션이 사용하는 포트를 노출 (기본은 8080)
EXPOSE 8080

# 애플리케이션 실행 명령
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
