version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: jdbc:log4jdbc:mariadb://db:3306/moneymany?useSSL=false&serverTimezone=UTC
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password   # 필요에 따라 설정하세요.
      MYSQL_DATABASE: moneymany
      MYSQL_USER: moneymany_user
      MYSQL_PASSWORD: manymoney
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: